"""empty message

Revision ID: 04f354fb62c7
Revises: a04c4422f6a5
Create Date: 2024-02-14 17:48:24.230867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f354fb62c7'
down_revision = 'a04c4422f6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=120), nullable=False),
    sa.Column('order_placement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.String(length=256), nullable=True),
    sa.Column('order_status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
