"""empty message

Revision ID: 115e3263d27e
Revises: 4871a9462d8d
Create Date: 2024-02-19 15:40:43.179302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115e3263d27e'
down_revision = '4871a9462d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
