"""empty message

Revision ID: 223a917cf8c7
Revises: 9a76b5d8d0c9
Create Date: 2024-02-29 13:22:38.168174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223a917cf8c7'
down_revision = '9a76b5d8d0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
