"""empty message

Revision ID: 27e3639ca7a0
Revises: cb96a4050da1
Create Date: 2024-02-19 13:00:46.156094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e3639ca7a0'
down_revision = 'cb96a4050da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###
