"""empty message

Revision ID: 28c71d01c8c2
Revises: 84bedb9d2732
Create Date: 2024-02-22 12:32:57.510698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c71d01c8c2'
down_revision = '84bedb9d2732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('inventory', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
