"""empty message

Revision ID: 2ad5e559c584
Revises: 48ff803b7357
Create Date: 2024-02-29 14:30:30.302790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ad5e559c584'
down_revision = '48ff803b7357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.drop_constraint('assigned_ibfk_3', type_='foreignkey')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assigned_ibfk_3', 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###
