"""empty message

Revision ID: 2b2968e8e395
Revises: 32d505ca6129
Create Date: 2024-02-29 11:06:10.824576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2968e8e395'
down_revision = '32d505ca6129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('assigned',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('product_id', sa.Integer(), nullable=True),
    # sa.Column('employee_id', sa.Integer(), nullable=True),
    # sa.Column('assignment_date', sa.Date(), nullable=True),
    # sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    # sa.ForeignKeyConstraint(['product_id'], ['inventory.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned')
    # ### end Alembic commands ###
