"""empty message

Revision ID: 32d505ca6129
Revises: ab3fe7e4913b
Create Date: 2024-02-29 11:02:45.964317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d505ca6129'
down_revision = 'ab3fe7e4913b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_date', sa.Date(), nullable=True))
        batch_op.drop_column('Assignment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Assignment_date', sa.DATE(), nullable=True))
        batch_op.drop_column('assignment_date')

    # ### end Alembic commands ###
