"""empty message

Revision ID: 4871a9462d8d
Revises: 27e3639ca7a0
Create Date: 2024-02-19 14:51:15.273465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4871a9462d8d'
down_revision = '27e3639ca7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
