"""empty message

Revision ID: 7a3db38e1108
Revises: db7da028954e
Create Date: 2024-02-20 18:22:49.539781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3db38e1108'
down_revision = 'db7da028954e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###
