"""empty message

Revision ID: 94723e529a47
Revises: cab5f5fcbd58
Create Date: 2024-03-03 15:58:10.504032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94723e529a47'
down_revision = 'cab5f5fcbd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('unique_code', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned', schema=None) as batch_op:
        batch_op.drop_column('unique_code')
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
