"""empty message

Revision ID: b96fababa42e
Revises: 9ceb9a7cde01
Create Date: 2024-02-21 23:04:32.971083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b96fababa42e'
down_revision = '9ceb9a7cde01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=80),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
