"""empty message

Revision ID: bcb812105cc9
Revises: c9b9c951bf75
Create Date: 2024-02-29 10:36:44.146549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcb812105cc9'
down_revision = 'c9b9c951bf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.drop_column('fname')
        batch_op.drop_column('lname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lname', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('fname', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
