"""empty message

Revision ID: c0fa499f27eb
Revises: 83099654efcc
Create Date: 2024-02-22 12:05:07.061851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0fa499f27eb'
down_revision = '83099654efcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', mysql.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
