"""empty message

Revision ID: c70b76730262
Revises: e28de9b4bf20
Create Date: 2024-02-21 15:54:03.838830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c70b76730262'
down_revision = 'e28de9b4bf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
