"""empty message

Revision ID: db7da028954e
Revises: 036e0159582c
Create Date: 2024-02-20 18:22:33.458647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db7da028954e'
down_revision = '036e0159582c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_ibfk_1', type_='foreignkey')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inventory_ibfk_1', 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###
