"""empty message

Revision ID: e052ef30d9a2
Revises: 2de59177d00f
Create Date: 2024-02-19 12:46:42.099733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e052ef30d9a2'
down_revision = '2de59177d00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', mysql.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
