"""empty message

Revision ID: e23890f3d793
Revises: 04f354fb62c7
Create Date: 2024-02-15 11:52:34.236704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e23890f3d793'
down_revision = '04f354fb62c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=120), nullable=False),
    sa.Column('order_placement_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.String(length=256), nullable=True),
    sa.Column('order_status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('price_per_unit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_type', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('order_placement_date', sa.DATE(), nullable=True),
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attachments', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('order_status', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transactions_model')
    # ### end Alembic commands ###
