"""empty message

Revision ID: f7a246b9a55e
Revises: c70b76730262
Create Date: 2024-02-21 16:33:07.597112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7a246b9a55e'
down_revision = 'c70b76730262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('roles_ibfk_2', type_='foreignkey')
        batch_op.drop_column('product_type_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('roles_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('roles_ibfk_1', 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###
